# Development Docker Compose file for AI Science Builder

# Development docker-compose with hot reload

services:
  # Backend Service (Development with hot reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-science-builder-backend-dev
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - FIREBASE_CREDENTIALS_PATH=/app/credentials/firebase-credentials.json
      - LEMON_SQUEEZY_API_KEY=${LEMON_SQUEEZY_API_KEY}
      - LEMON_SQUEEZY_STORE_ID=${LEMON_SQUEEZY_STORE_ID}
      - DEBUG=True
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      # Mount credentials
      - ./backend/firebase-credentials.json:/app/credentials/firebase-credentials.json:ro
      # Exclude Python cache
      - /app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    networks:
      - ai-science-builder-network

  # Frontend Service (Development with hot reload)
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ai-science-builder-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - ai-science-builder-network

networks:
  ai-science-builder-network:
    driver: bridge

